### ISSUE TITLE
Elastic search data maintenance

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#277]
Describe a way to for basic data maintenance to for example delete logged messages that are older than 3 month.
Might ‘split’ and ‘shrink’ shards, for example create one shard per month and then delete older ones.

**Comment by es-sns121** [comment]
There seem to be two options for managing elastic search data by date.

1. **Delete documents older than a specific date using the query APIs.**

This would entail using a chron job and curl to send a "delete by query" message to elastic search (reference 1).

For example, 
```
curl -X POST "localhost:9200/accel_alarms/_delete_by_query" -H 'Content-Type: application/json' -d'
{
    "query":
    {
         "range" : 
          {
               "@timestamp" : 
               {
                    "gte" : "08/01/2018",
                    "lte" : "09/01/2018",
                    "format": "dd/MM/yyyy||yyyy"
               }
          }
    }
}
'
```
This method of deleting the messages using the query APIs allows for the use of single index, however the query operation would likely take a long time.

The favoured option and the one proposed by elastic search developers who are asked this question is the following option (reference 1).

2. **Using time based indices and deleting ones past a certain date with elastic curator.**

Using time based indices would entail creating a new index every week (or day, month, year...) and then deleting the indices as they become outdated. This deletion is managed by a program called curator, part of the elastic stack (reference 5). Having multiple indices does not complicate queries as elastic search handles searches across multiple indices under the hood. It "intelligently" grabs the indices it needs for the given search dates (reference 1).

**References:**

1. https://discuss.elastic.co/t/delete-documents-by-timestamp/92058/11
2. https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-shrink-index.html
3. https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-split-index.html
4. https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html
5. https://www.elastic.co/guide/en/elasticsearch/client/curator/current/about-features.html

**Future Reading:**

1. https://www.elastic.co/blog/managing-time-based-indices-efficiently

**Comment by es-sns121** [comment]
**Curator**

- **Install**
```sudo pip install elasticsearch-curator```
- **config file (YAML)**
```
---
client:
  hosts:
    - localhost
  port: 9200
  use_ssl: False
  ssl_no_validate: False
  http_auth: False
  timeout: 30
  master_only: True
logging:
  loglevel: INFO
  logfile:
  logformat: default
```
   - **actions file (YAML)**
```
---
actions:
  1:
    action: delete_indices
    description: >-
      delete indices older than a month.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: accelerator_alarms_
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
```
- **Running**
```curator --config /path/to/config.yml /path/to/actions.yml```

**Comment by es-sns121** [comment]
To run curator and see the actions it will take without actually completing the actions, you can use the "dry run" feature.

```curator --config /path/to/config.yml /path/to/actions.yml --dry-run ```

Curator will the process the actions file but not actually complete the actions.

**Comment by es-sns121** [comment]
**Possible Curator Setup**
- **config file (YAML)**
```
---
client:
  hosts:
    - localhost
  port: 9200
  use_ssl: False
  ssl_no_validate: False
  http_auth: False
  timeout: 30
  master_only: True
logging:
  loglevel: INFO
  logfile:
  logformat: default
```
- **actions file (YAML)**
```
---
actions:
  1:
    action: delete_indices
    description: >-
      delete indices older than three months.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: accelerator_alarms_
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 90
 2:
    action: create_index
    description: "Create weekly index"
    options:
     name: '<accelerator_alarms_{now/d +1d}>'
     # ...
     extra_settings:
         settings:
           number_of_shards: 1
           number_of_replicas: 0
         mappings:
           alarm:
             properties:
               APPLICATION-ID:
                 type: text
                 index: not_analyzed
               config:
                 type: keyword
               pv:
                 type: text
                 analyzer: keyword
              severity:
                 type: keyword
              message:
                 type: text
              value:
                 type: text
              time:
                 type: date
                 format: yyyy-MM-dd HH:mm:ss.SSS
              current_severity:
                 type:keyword
              current_message: 
                 type:text
              mode:
                 type: text
```
 - **crontab** 
```
0 0 * * 0 curator --config /path/to/config.yml /path/to/actions.yml
```

Runs every week on Sunday at midnight. Names index 'accelerator_alarms_date' where date is Monday's date.
